# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SMF=y

# Fancy logging.
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_INFO_COLOR_GREEN=y
CONFIG_LOG_DBG_COLOR_BLUE=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_CPU_LOAD=y

# Screen things
CONFIG_DISPLAY=y
CONFIG_INPUT=y
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=32768
CONFIG_LV_Z_VDB_SIZE=10
CONFIG_LV_Z_DOUBLE_VDB=y
CONFIG_LV_Z_VDB_ALIGN=2
CONFIG_LV_BUILD_EXAMPLES=n
CONFIG_LV_BUILD_DEMOS=n
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y

# Bluetooth features
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="cave-gems-app"
# BT_APPEARANCE_PORTABLE_HANDHELD_CONSOLE
CONFIG_BT_DEVICE_APPEARANCE=2690
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_MAX_CONN=8
CONFIG_BT_GATT_CLIENT=y
