CONFIG_SDL_DISPLAY_ZOOM_PCT=200
CONFIG_DEBUG_OPTIMIZATIONS=y

# Not supported on the sim (not useful anyways)
CONFIG_CPU_LOAD=n

# Extra debug info on sim.
CONFIG_SYS_HEAP_RUNTIME_STATS=y

# Seems to be reuqired to make LVGL responsive on the sim (at least through wsl 2)
CONFIG_LV_DEF_REFR_PERIOD=16
